/**
 * Alltimezone exports a static `timezones` array used to populate timezone
 * dropdowns. The data is generated by hand and easy to drift, so the tests
 * here lock down the shape of each entry, basic invariants on offsets, and
 * a handful of well-known zones.
 */
import { describe, it, expect } from "vitest";
import { timezones } from "../../../src/utils/Alltimezone.jsx";

describe("utils/Alltimezone", () => {
  it("exports a non-empty array", () => {
    expect(Array.isArray(timezones)).toBe(true);
    expect(timezones.length).toBeGreaterThan(50);
  });

  it("each entry has zone, name and offset of the right shape", () => {
    for (const tz of timezones) {
      expect(typeof tz.zone).toBe("string");
      expect(tz.zone.length).toBeGreaterThan(0);
      expect(typeof tz.name).toBe("string");
      expect(tz.name.length).toBeGreaterThan(0);
      expect(typeof tz.offset).toBe("number");
      expect(Number.isFinite(tz.offset)).toBe(true);
    }
  });

  it("offsets stay within plausible bounds (-14h to +14h in seconds)", () => {
    for (const tz of timezones) {
      expect(tz.offset).toBeGreaterThanOrEqual(-14 * 3600);
      expect(tz.offset).toBeLessThanOrEqual(14 * 3600);
    }
  });

  it("contains UTC reference zones (offset 0)", () => {
    const utcs = timezones.filter((tz) => tz.offset === 0);
    expect(utcs.length).toBeGreaterThan(0);
    // Spot-check a handful of expected UTC zones
    const zones = utcs.map((tz) => tz.zone);
    expect(zones).toContain("Africa,Accra");
  });

  it("includes well-known positive and negative offsets", () => {
    const india = timezones.find((tz) => tz.zone.includes("Calcutta") || tz.zone.includes("Kolkata"));
    if (india) {
      // India Standard Time is UTC+05:30 (19800s)
      expect(india.offset).toBe(19800);
    }
    const tokyo = timezones.find((tz) => tz.zone === "Asia,Tokyo");
    if (tokyo) {
      // Japan is UTC+09:00
      expect(tokyo.offset).toBe(9 * 3600);
    }
  });

  it("has no duplicate `zone` keys", () => {
    const seen = new Set();
    for (const tz of timezones) {
      expect(seen.has(tz.zone)).toBe(false);
      seen.add(tz.zone);
    }
  });

  it("name strings encode the offset in `UTC ±HH:MM` form", () => {
    // Just spot-check a few — the underlying data uses this format.
    for (const tz of timezones.slice(0, 20)) {
      expect(tz.name).toMatch(/UTC [+-]\d{2}:\d{2}/);
    }
  });
});
