import express from "express";
import nvrRoutes from "../../core/v1/NVR/nvr.routes.js";
import channelRoutes from "../../core/v1/channels/channels.routes.js";
import authRoutes from "../../core/v1/Auth/auth.routes.js";
import incidentsRoutes from "../../core/v1/incidents/incidents.routes.js";
import verifyToken from "../../middlewares/verifyToken.js";
import alertRoutes from "../../core/v1/alerts/alerts.routes.js";
import recipientsRoutes from "../../core/v1/verifyRecipients/recipients.routes.js";
import adminRoutes from "../../core/v1/admin/admin.routes.js";
import dashboardRoutes from "../../core/v1/dashboard/dashboard.routes.js";
import authorizedUsersRoutes from "../../core/v1/authorizedUsers/authorizedUsers.routes.js";
import faceImagesRoutes from "../../core/v1/faceImages/faceImages.routes.js";
import analyticsRoutes from "../../core/v1/analytics/analytics.routes.js";
import telegramRoutes from "../../core/v1/telegram/telegram.routes.js";
import clientConfigRoutes from "../../core/v1/clientConfig/clientConfig.routes.js";
import detectionSettingsRoutes from "../../core/v1/detectionSettings/detectionSettings.routes.js";
import uploadRoutes from "../../core/v1/Uploads/uploads.routes.js";
import storageRoutes from "../../core/v1/storage/storage.routes.js";
import rolesRoutes from "../../core/v1/roles/roles.routes.js";
import departmentRoutes from "../../core/v1/departments/departments.routes.js";
import profilesRoutes from "../../core/v1/profiles/profiles.routes.js";
import attendanceRoutes from "../../core/v1/attendance/attendance.routes.js";
import accessLogsRoutes from "../../core/v1/accesslogs/accesslogs.routes.js";
import authorizedObjectsRoutes from "../../core/v1/authorizedObjects/authorizedObjects.routes.js";
import permissionsRoutes from "../../core/v1/permission/permissions.route.js";
import usersRoutes from "../../core/v1/users/users.routes.js";
import authorizedChannels from "../../core/v1/cameraRestrictions/authorizedChannels.routes.js";
import domainRoutes from "../../core/v1/domain/domain.routes.js";
import detectionObjectsRoutes from "../../core/v1/detectionObjects/objects.routes.js";
import shiftRoutes from "../../core/v1/shifts/shifts.routes.js";
import autoEmailReportRoutes from "../../core/v1/autoEmailReport/autoEmailReport.routes.js";
import jobsRoutes from "../../core/v1/jobs/jobs.routes.js";
import entryRoutes from "../../core/v1/entry/entry.routes.js";
import vehicleRoutes from "../../core/v1/vehicle/vehicle.routes.js";
import locationRoutes from "../../core/v1/locations/location.routes.js";

const router = express.Router();

router.use("/auth", authRoutes);
router.use("/uploads", uploadRoutes);
router.use("/admin", adminRoutes);
router.use("/authorizedUsers", authorizedUsersRoutes);
router.use("/faceImages", faceImagesRoutes);
router.use("/authorizedChannels", authorizedChannels);
router.use("/users", usersRoutes);
router.use("/nvr", verifyToken, nvrRoutes);
router.use("/channel", verifyToken, channelRoutes);
router.use("/auth", authRoutes);
router.use("/uploads", uploadRoutes);
router.use("/incidents", verifyToken, incidentsRoutes);
router.use("/alert", verifyToken, alertRoutes);
router.use("/recipients", recipientsRoutes);
router.use("/dashboard", verifyToken, dashboardRoutes);
router.use("/analytics", verifyToken, analyticsRoutes);
router.use("/authorizedUsers", verifyToken, authorizedUsersRoutes);
router.use("/authorizedObjects", verifyToken, authorizedObjectsRoutes);
router.use("/detection-settings", verifyToken, detectionSettingsRoutes);
router.use("/storage", storageRoutes);
router.use("/profiles", verifyToken, profilesRoutes);
router.use("/attendance", verifyToken, attendanceRoutes);
router.use("/roles", verifyToken, rolesRoutes);
router.use("/departments", verifyToken, departmentRoutes);
router.use("/accessLogs", verifyToken, accessLogsRoutes);
router.use("/permissions", verifyToken, permissionsRoutes);
router.use("/auto-email-report", verifyToken, autoEmailReportRoutes);
router.use("/domain", domainRoutes);
router.use("/detection-objects", verifyToken, detectionObjectsRoutes);
router.use("/shifts", verifyToken, shiftRoutes);
router.use("/jobs", verifyToken, jobsRoutes);
router.use("/entry", verifyToken, entryRoutes);
router.use("/vehicle", verifyToken, vehicleRoutes);
router.use("/locations", verifyToken, locationRoutes);
// Telegram: /link-code + /unlink are authed inside the router; /webhook is
// public (Telegram calls it), so mount WITHOUT a router-level verifyToken.
router.use("/telegram", telegramRoutes);
// clientConfig.routes.js applies verifyToken per-route, so mount plain.
router.use("/client-config", clientConfigRoutes);

export default router;
